- name: install php-fpm 
  apt: 
    pkg: "{{ php_fpm }}"
    state: "{{ php_fpm_state }}"
    update_cache: "{{ apt_update_cache }}"

- name: install php modules
  apt:
    pkg: "{{ item }}"
  with_items: "{{ php_modules }}"
